repos:
  - hooks:
      - additional_dependencies:
          - eslint@8.42.0
          - eslint-plugin-prettier@4.2.1
        args:
          - --config
          - javascript.eslintrc.yaml
          - --fix
        files: \.[j]sx?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.5.0
  - hooks:
      - args:
          - --single-quote
          - --trailing-comma
          - all
        id: prettier
        types_or:
          - css
          - javascript
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
  - hooks:
      - additional_dependencies:
          - eslint@8.42.0
          - '@typescript-eslint/eslint-plugin@5.59.11'
          - '@typescript-eslint/parser@5.59.11'
          - typescript@5.1.3
          - eslint-config-prettier@8.8.0
          - eslint-plugin-prettier@4.2.1
        args:
          - --config
          - typescript.eslintrc.yaml
          - --fix
        files: \.[t]sx?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.5.0
  - hooks:
      - args:
          - --single-quote
          - --trailing-comma
          - all
        id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
  - hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - args:
          - --allow-missing-credentials
        id: detect-aws-credentials
      - id: detect-private-key
      - args:
          - --pytest-test-first
        id: name-tests-test
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: detect-secrets
    repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
