name: publish-to-github-pages
on:
  push:
    branches:
      - main
      - debug

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Node.js CI
        uses: ./.github/workflows/setup-node

      - name: Setup GH Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build static Next.js site
        run: npx next build

      - name: debug pwd
        run: pwd && ls -a

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
